# This extends the completion script generated by clap_complete

function _gitlasso_complete_git
    set -l tokens (commandline -opc) (commandline -ct)
    set -l index (contains -i git (commandline -opc))
    complete -C"$tokens[$index..]"
end

complete -c '<BINARY>' -n '__fish_<BINARY>_using_subcommand git' -a '(_gitlasso_complete_git)'
